name: flutteramp
services:
  # Development services
  postgres:
    image: postgres:16.3
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: flutteramp
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:?}"
    volumes:
      - flutteramp_data:/var/lib/postgresql/data
    profiles:
      - "" # Default profile
      - dev


  pgduckdb:
    image: pgduckdb/pgduckdb:17-main
    ports:
      - "8092:5432"
    environment:
      POSTGRES_PASSWORD: "${PGDUCKDB_POSTGRES_PASSWORD:?}"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    profiles:
      - "" # Default profile
      - dev

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "$${REDIS_PASSWORD}"
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD="${REDIS_PASSWORD:?}"
    profiles:
      - "" # Default profile
      - dev

  # Test services
  postgres_test:
    image: postgres:16.3
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: flutteramp_test
      POSTGRES_PASSWORD: "${POSTGRES_TEST_POSTGRES_PASSWORD:?}"
    volumes:
      - flutteramp_test_data:/var/lib/postgresql/data
    profiles:
      - "" # Default profile
      - test
  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "${REDIS_TEST_PASSWORD:?}"
    environment:
      REDIS_REPLICATION_MODE: master
      REDIS_TEST_PASSWORD: "${REDIS_TEST_PASSWORD:?}"
    profiles:
      - "" # Default profile
      - test

  proxy:
    image: nginx:1.27.3
    ports:
      - 8009:80
    command: /bin/bash -c "envsubst '$$SETLIST_FM_API_KEY' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/default.conf.template
      - proxy_cache:/var/cache/nginx
    environment:
      SETLIST_FM_API_KEY: "${SETLIST_FM_API_KEY:?}"

volumes:
  flutteramp_data:
  flutteramp_test_data:
  proxy_cache:
