name: flutteramp_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  serverpod: ^2.4.0
  dio: ^5.8.0+1
  sprintf: ^7.0.0
  intl: ^0.20.2

dev_dependencies:
  lints: '>=3.0.0 <6.0.0'
  test: '^1.24.2'
  serverpod_test: ^2.4.0

